#pragma once

//? Array of keys and then an enum with their position in the array.

enum {
    KEY_A = 0,
    KEY_B = 1,
    KEY_C = 2,
    KEY_D = 3,
    KEY_E = 4,
    KEY_F = 5,
    KEY_G = 6,
    KEY_H = 7,
    KEY_I = 8,
    KEY_J = 9,
    KEY_K = 10,
    KEY_L = 11,
    KEY_M = 12,
    KEY_N = 13,
    KEY_O = 14,
    KEY_P = 15,
    KEY_Q = 16,
    KEY_R = 17,
    KEY_S = 18,
    KEY_T = 19,
    KEY_U = 20,
    KEY_V = 21,
    KEY_W = 22,
    KEY_X = 23,
    KEY_Y = 24,
    KEY_Z = 25,
    KEY_1 = 26,
    KEY_2 = 27,
    KEY_3 = 28,
    KEY_4 = 29,
    KEY_5 = 30,
    KEY_6 = 31,
    KEY_7 = 32,
    KEY_8 = 33,
    KEY_9 = 34,
    KEY_0 = 35,
    KEY_ENTER = 36,
    KEY_ESC = 37,
    KEY_BACKSPACE = 38,
    KEY_TAB = 39,
    KEY_SPACE = 40,
    KEY_LEFT = 41,
    KEY_RIGHT = 42,
    KEY_UP = 43,
    KEY_DOWN = 44,
    KEY_PAGE_UP = 45,
    KEY_PAGE_DOWN = 46,
    KEY_COUNT = 47,
};

//? This array just tells us whether said key is pressed or not.
const int keys[KEY_COUNT] = {0};